bazar/urls.py
from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastro/delete/<int:cadastro_id>/', views.cadastro_delete, name='cadastro_delete'),
    path('recibo/', views.recibo_lista, name='recibo_lista'),
    path('recibo/novo/<int:senha>/', views.recibo_novo, name='recibo_novo'),
    path('recibo/imprimir/<int:recibo_id>/', views.recibo_imprimir, name='recibo_imprimir'),
    path('recibo/delete/<int:recibo_id>/', views.recibo_delete, name='recibo_delete'),
    path('export/', views.export_excel, name='export_excel'),

]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class CreatedUpdatedModel(models.Model):
    criado_em = models.DateTimeField(u'Criado em', auto_now_add=True, editable=False)
    criado_por = models.ForeignKey(User,
                                   related_name="created_%(app_label)s_%(class)s_set",
                                   null=True, editable=False, on_delete=models.SET_NULL)
    atualizado_em = models.DateTimeField(u'Atualizado em', auto_now=True, editable=False)
    atualizado_por = models.ForeignKey(User,
                                       related_name="modified_%(app_label)s_%(class)s_set",
                                       null=True, editable=False, on_delete=models.SET_NULL)

    class Meta:
        abstract = True


class Cadastro(CreatedUpdatedModel):
    data_hora = models.DateTimeField('Data/Hora', auto_now_add=True)
    senha = models.IntegerField('Senha', unique=True)
    nome = models.CharField('Nome', max_length=200)
    cpf = models.CharField('CPF', max_length=11)
    email = models.EmailField('E-mail', null=True, blank=True)

    def cpf_format(self):
        return "{}.{}.{}-{}".format(self.cpf[0:3], self.cpf[3:6], self.cpf[6:9], self.cpf[9:11])

    class Meta:
        ordering = ['-senha']

    def __str__(self):
        return self.nome


class Recibo(CreatedUpdatedModel):
    cadastro = models.ForeignKey(Cadastro, verbose_name='Cadastro', on_delete=models.PROTECT)
    data_hora = models.DateTimeField('Data/Hora', auto_now_add=True)
    brinquedo_qt = models.PositiveIntegerField('Brinquedos Qtd', default=0)
    brinquedo_vl = models.DecimalField('Brinquedos Valor', max_digits=10, decimal_places=2, default=0)
    bazar_qt = models.PositiveIntegerField('Artigos de Bazar Qtd', default=0)
    bazar_vl = models.DecimalField('Artigos de Bazar Valor', max_digits=10, decimal_places=2, default=0)
    eletro_qt = models.PositiveIntegerField('Equipamentos Eletrônicos Qtd', default=0)
    eletro_vl = models.DecimalField('Equipamentos Eletrônicos Valor', max_digits=10, decimal_places=2, default=0)
    relogio_qt = models.PositiveIntegerField('Relógios Qtd', default=0)
    relogio_vl = models.DecimalField('Relógios Vlr', max_digits=10, decimal_places=2, default=0)
    musical_qt = models.PositiveIntegerField('Instrumentos Musicais, Mesas e Módulos Qtd', default=0)
    musical_vl = models.DecimalField('Instrumentos Musicais, Mesas e Módulos Valor', max_digits=10, decimal_places=2, default=0)
    vestuario_qt = models.PositiveIntegerField('Vestuário Qtd', default=0)
    vestuario_vl = models.DecimalField('Vestuário Valor', max_digits=10, decimal_places=2, default=0)
    perfume_qt = models.PositiveIntegerField('Higiene Pessoal, Perfumes e Cosméticos Qtd', default=0)
    perfume_vl = models.DecimalField('Higiene Pessoal, Perfumes e Cosméticos Valor', max_digits=10, decimal_places=2, default=0)
    total = models.DecimalField('Valor Total', editable=False, max_digits=12, decimal_places=2, default=0)


    class Meta:
        ordering = ['-data_hora']

    def __str__(self):
        return self.cadastro.nome

core/forms.py
import datetime
from django import forms
from localflavor.br.forms import BRCPFField
from core.models import Cadastro, Recibo


class CadastroForm(forms.ModelForm):
    cpf = BRCPFField(max_length=11, min_length=11)

    class Meta:
        model = Cadastro
        fields = [
            'senha',
            'nome',
            'cpf',
            'email'
        ]


class ReciboForm(forms.ModelForm):
    brinquedo_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)
    bazar_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)
    eletro_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)
    relogio_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)
    musical_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)
    vestuario_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)
    perfume_vl = forms.DecimalField(max_digits=10, decimal_places=2, localize=True)

    class Meta:
        model = Recibo
        fields = [
            'brinquedo_qt',
            'brinquedo_vl',
            'bazar_qt',
            'bazar_vl',
            'eletro_qt',
            'eletro_vl',
            'relogio_qt',
            'relogio_vl',
            'musical_qt',
            'musical_vl',
            'vestuario_qt',
            'vestuario_vl',
            'perfume_qt',
            'perfume_vl'
        ]

templates/_base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static  'img/favicon.ico' %}">
    <title>Bazar</title>
    <link href="{% static  'bootstrap-4.0.0/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" >
    <link href="{% static  'css/main.css' %}" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">BAZAR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cadastro' %}">Cadastro</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recibo_lista' %}">Recibo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'export_excel' %}">Excel</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span>&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
    </main>

    <script src="{% static  'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static  'bootstrap-4.0.0/js/bootstrap.min.js' %}"></script>
    <script src="{% static  'js/jquery.mask.min.js' %}"></script>
    <script src="{% static  'js/CPF.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/cadastro.html
{% extends '_base.html' %}
{% load widget_tweaks %}

{% block content %}
<div>
    <h2>Cadastro</h2>

     <form action="{% url 'cadastro' %}" method="post" novalidate>
     {% csrf_token %}
        <div class="row">
          <div class="col-6">
            {{ form.senha.label_tag }}
            {% render_field form.senha class="form-control" value=nova_senha %}
            {% if form.senha.errors %}
                {% for error in form.senha.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {%  endfor %}
            {% endif %}
          </div>
          <div class="col-6">
            {{ form.cpf.label_tag }}
            {% render_field form.cpf class="form-control" %}
            {% if form.cpf.errors %}
                {% for error in form.cpf.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {%  endfor %}
            {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            {{ form.nome.label_tag }}
            {% render_field form.nome class="form-control" %}
              {% if form.nome.errors %}
                {% for error in form.nome.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {%  endfor %}
            {% endif %}
            </div>
          <div class="col-6">
            {{ form.email.label_tag }}
            {% render_field form.email class="form-control" %}
              {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {%  endfor %}
            {% endif %}
          </div>
        </div>
        <hr class="mb-6">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Salvar</button>
    </form>

    <hr class="mb-6">

    <table class="table table-striped table-sm">
      <thead>
        <tr class="table-primary">
          <th scope="col">Senha</th>
          <th scope="col">CPF</th>
          <th scope="col">Nome</th>
          <th scope="col">E-mail</th>
            <th></th>
        </tr>
      </thead>
      <tbody>
    {% if cadastros %}
        {% for cad in cadastros %}
         <tr>
          <th scope="row">{{ cad.senha }}</th>
          <td>{{ cad.cpf }}</td>
          <td>{{ cad.nome }}</td>
          <td>{{ cad.email|default_if_none:"" }}</td>
         <td>
             <a class="btn btn-danger btn-sm" href="{% url 'cadastro_delete' cad.id %}" aria-label="Delete">
              <i class="fa fa-trash-o fa-sm" aria-hidden="true"></i></a>
             <a class="btn btn-primary btn-sm" href="{% url 'recibo_novo' cad.senha %}" aria-label="Emitir Recibo">
              <i class="fa fa-shopping-cart fa-sm" aria-hidden="true"></i></a>
         </td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
          <th scope="row" colspan="4">Nenhum registro encontrado.</th>
        </tr>
    {% endif %}
       </tbody>
    </table>

    <nav aria-label="Paginação">
      <ul class="pagination justify-content-center">
      {% if cadastros.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">Primeira</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ cadastros.previous_page_number }}">Anterior</a></li>
      {% endif %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Página {{ cadastros.number }} de {{ cadastros.paginator.num_pages }}</a>
            </li>
      {% if cadastros.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ cadastros.next_page_number }}">Próxima</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ cadastros.paginator.num_pages }}">Última</a></li>
      {% endif %}
      </ul>
    </nav>


</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$( document ).ready(function() {
    edCpf = $("#id_cpf");
    edCpf.focus().select();
    edCpf.keyup(function() {
       $(this).val(this.value.replace(/\D/g, ''));
    });
    edCpf.on('keypress', function (e) {
        if(e.ctrlKey === true){
            if(e.keyCode === 17){
                $('#id_cpf').val(CPF.generate('digits'));
            }
        }
    });

});
</script>
{% endblock %}

templates/index.html
{% extends '_base.html' %}
{% load static from staticfiles %}
{% load humanize %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
</div>

      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Cadastros</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ qtd_cadastro }}</h1>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Total Vendas</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">R$ {{  total_vendas.total__sum|default_if_none:0|floatformat:"0"|intcomma }}</h1>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Média por Cadastro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">R$ {{ media_vendas.total__avg|default_if_none:0|floatformat:"0"|intcomma }}</h1>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
      <table class="table table-striped table-sm ">
      <thead>
        <tr>
          <th scope="col">Data</th>
          <th scope="col">Qtd</th>
          <th scope="col">Valor</th>
        </tr>
      </thead>
      <tbody>
      {% if vendas_por_dia %}
        {% for vd in vendas_por_dia %}
         <tr>
          <th scope="row">{{ vd.dia|date:"d/m/Y" }}</th>
          <td>{{ vd.qtd }}</td>
          <td>{{ vd.total|floatformat:"0"|intcomma }}</td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <th scope="row" colspan="4">Nenhum registro encontrado.</th>
        </tr>
      {% endif %}
       </tbody>
    </table>
        </div>
          <div class="col-6"></div>
      </div>

    <canvas class="my-4" id="myChart" width="900" height="380"></canvas>

{% endblock %}

{% block javascript %}
    <script src="{% static  'js/Chart.min.js' %}"></script>
    <script type="text/javascript">
    var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: [
              {% for ch in cad_por_hora %}
                "{{ ch.hora }}"{% if not forloop.last %},{% endif %}
              {% endfor %}
          ],
          datasets: [{
            data: [
                {% for ch in cad_por_hora %}
                    {{ ch.qtd }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            ],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
{% endblock %}

templates/recibo_dados.html
<table class="tabelaPagina">
      <tr>
          <td><b>Associacao Congregacao de Santa Catarina</b><br>
            Av Paulista, N 200 – Bela Vista – SP<br>
            CNPJ nº 60.922.168/0001-86<br>
            www.acsc.org.br<br>
          </td>
        <td colspan="2">
            Recibo nº: {{ rec.id }} <br><br>
            Senha  nº: {{ rec.cadastro.senha }}<br>
        </td>
      </tr>
      <tr>
          <td colspan="3">Recebemos de {{ rec.cadastro.nome }}, CPF: {{ rec.cadastro.cpf_format }} a importância de R$ {{ rec.total }} referente a aquisição dos itens abaixo elencados no bazar do hospital São José com mercadorias apreendidas pela RECEITA FEDERAL.</td>
      </tr>
        <tr>
        <td><b>Item</b></td>
        <td><b>Qtd.</b></td>
        <td><b>Valor</b></td>
       </tr>
        <tr>
        <td>Brinquedos</td>
        <td>{{ rec.brinquedo_qt }}</td>
        <td>R$ {{ rec.brinquedo_vl }}</td>
       </tr>
       <tr>
        <td>Artigos de Bazar</td>
        <td>{{ rec.bazar_qt }}</td>
        <td>R$ {{ rec.bazar_vl }}</td>
       </tr>
       <tr>
        <td>Equipamentos Eletrônicos</td>
        <td>{{ rec.eletro_qt }}</td>
        <td>R$ {{ rec.eletro_vl }}</td>
       </tr>
       <tr>
        <td>Relógios</td>
        <td>{{ rec.relogio_qt }}</td>
        <td>R$ {{ rec.relogio_vl }}</td>
       </tr>
       <tr>
        <td>Instrumentos Musicais, Mesas e Módulos</td>
        <td>{{ rec.musical_qt }}</td>
        <td>R$ {{ rec.musical_vl }}</td>
       </tr>
       <tr>
        <td>Vestuário</td>
        <td>{{ rec.vestuario_qt }}</td>
        <td>R$ {{ rec.vestuario_vl }}</td>
       </tr>
       <tr>
        <td>Higiene Pessoal, Perfumes e Cosméticos</td>
        <td>{{ rec.perfume_qt }}</td>
        <td>R$ {{ rec.perfume_vl }}</td>
       </tr>
        <tr>
        <td colspan="3">
            "AS MERCADORIAS NÃO PODERÃO SER UTILIZADAS PARA A VENDA NO COMÉRCIO, SOB PENA DE APREENSÃO POR PARTE DAS AUTORIDADES COMPETENTES"<br>
            "OS PRODUTOS NÃO SERÃO TESTADOS E NÃO SERÁ PERMITIDA A TROCA E/OU SUBSTITUIÇÃO DE MERCADORIAS COM EVENTUAIS FALHAS"
        </td>
       </tr>
        <tr>
        <td ><br><br>
            ___________________________________________________________<br>
            <span style="padding-left: 180px;">TESOURARIA</span>
        </td>
        <td colspan="2">{{ rec.data_hora }}</td>
       </tr>

    </table>

templates/recibo_imprimir.html
{% load static from staticfiles %}
{% load helpers %}
<!doctype html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <title>Recibo</title>
    <style type="text/css">
    * {
        background:transparent !important;
        color:#000;
    }
    body {
        margin:0;
        padding:0;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        color: #000;
        font-size: 10pt;
    }
    @page {
        margin: 1cm;
    }
    .tabelaPagina {
        width: 710px;
        border: 1px solid #000;
        border-spacing: 0;
        padding: 0;
        background: #FFF;
    }
    .tabelaPagina td {
	    border: 1px solid #000;
        padding: 5px;
    }
    </style>
  </head>
  <body>
    {% include "recibo_dados.html" %}
    <div style="page-break-after: always;"></div>
    {% include "recibo_dados.html" %}
    <div style="page-break-after: always;"></div>
    {% include "recibo_dados.html" %}
  <script src="{% static  'js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript">
      $( document ).ready(function() {
        window.print();
      });
</script>
  </body>
</html>

templates/recibo_lista.html
{% extends '_base.html' %}

{% block content %}

<div>
    <h2>Lista de Recibos</h2>

    <hr>

    <form class="form-inline">
      <div class="form-group mx-sm-3 mb-2">
        <label for="id_cadastro" style="margin-right: 15px;">Senha: </label>
        <input type="text" class="form-control" id="id_cadastro">
      </div>
      <button type="submit" class="btn btn-primary mb-2" id="btn_novo">Novo Recibo</button>
    </form>

    <hr>

    <table class="table table-striped table-sm">
      <thead>
        <tr class="table-primary">
          <th scope="col">Numero</th>
          <th scope="col">Senha</th>
          <th scope="col">CPF</th>
          <th scope="col">Nome</th>
          <th scope="col">Valor Total</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    {% if recibos %}
        {% for rec in recibos %}
         <tr>
          <th scope="row">{{ rec.id }}</th>
          <td>{{ rec.cadastro.senha }}</td>
          <td>{{ rec.cadastro.cpf }}</td>
          <td>{{ rec.cadastro.nome }}</td>
          <td>{{ rec.total }}</td>
          <td>
              <a class="btn btn-danger btn-sm" href="{% url 'recibo_delete' rec.id %}" aria-label="Delete">
              <i class="fa fa-trash-o fa-sm" aria-hidden="true"></i></a>
              <a class="btn btn-primary btn-sm" href="#" onclick="openPrintDialogue({{ rec.id}} );" aria-label="Impimir Recibo">
              <i class="fa fa-print fa-sm" aria-hidden="true"></i></a>
          </td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
          <th scope="row" colspan="5">Nenhum registro encontrado.</th>
        </tr>
    {% endif %}
       </tbody>
    </table>
</div>

{% endblock %}
{% block javascript %}
<script type="text/javascript">
$( document ).ready(function() {
    $("#id_cadastro").focus().select();

    $("#btn_novo").click(function(e) {
        e.preventDefault();
        var senha = $("#id_cadastro").val();

        if ($.isNumeric(senha)) {
            window.location.href = "/recibo/novo/" + senha;
        } else {
            alert("Insira um número válido no campo Senha.");
        }
    });
});

function openPrintDialogue(recibo){
  $('<iframe>', {
    name: 'print_iframe',
    class: 'printFrame'
  }).appendTo('body').attr('src', '/recibo/imprimir/' + recibo +  '/');

  window.frames['print_iframe'].focus();

  setTimeout(() => { $(".printFrame").remove(); }, 1000)
};


</script>
{% endblock %}

templates/recibo_novo.html
{% extends '_base.html' %}

{% block content %}

<div>
    <h2>Novo Recibo</h2>
    {{ form.non_field_errors }}

    {% for field in form.visible_fields %}
          {{ field.errors }}
    {% endfor %}



<form action="{% url 'recibo_novo' cadastro.senha %}" method="post">
    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}
    <table>
      <tr>
        <td>Senha:</td>
        <td colspan="2">{{ cadastro.senha }}</td>
      </tr>
      <tr>
        <td>CPF:</td>
        <td colspan="2">{{ cadastro.cpf }}</td>
      </tr>
      <tr>
        <td>Nome:</td>
        <td colspan="2">{{ cadastro.nome }}</td>
      </tr>
      <tr>
        <td>Valor acumulado compras:</td>
        <td colspan="2" style="color: {{ cor_alerta }}">R$ {{ soma_compras.total_compras|default_if_none:0 }}</td>
      </tr>
      <tr>
        <td colspan="3"><hr></td>
      </tr>

      <tr>
        <td></td>
        <td>Qtd</td>
        <td>Valor</td>
       </tr>
       <tr>
        <td>Brinquedos</td>
        <td><input type="number" name="brinquedo_qt" value="0" min="0" required id="id_brinquedo_qt" class="form-control" /></td>
        <td><input type="text" name="brinquedo_vl" value="0,00" required id="id_brinquedo_vl" class="form-control edValor" /></td>
       </tr>
       <tr>
        <td>Artigos de Bazar</td>
        <td><input type="number" name="bazar_qt" value="0" min="0" required id="id_bazar_qt" class="form-control" /></td>
        <td><input type="text" name="bazar_vl" value="0,00" required id="id_bazar_vl" class="form-control edValor" /></td>
       </tr>
       <tr>
        <td>Equipamentos Eletrônicos</td>
        <td><input type="number" name="eletro_qt" value="0" min="0" required id="id_eletro_qt" class="form-control" /></td>
        <td><input type="text" name="eletro_vl" value="0,00" required id="id_eletro_vl" class="form-control edValor" /></td>
       </tr>
       <tr>
        <td>Relógios</td>
        <td><input type="number" name="relogio_qt" value="0" min="0" required id="id_relogio_qt"class="form-control" /></td>
        <td><input type="text" name="relogio_vl" value="0,00" required id="id_relogio_vl" class="form-control edValor" /></td>
       </tr>
       <tr>
        <td>Instrumentos Musicais, Mesas e Módulos</td>
        <td><input type="number" name="musical_qt" value="0" min="0" required id="id_musical_qt" class="form-control" /></td>
        <td><input type="text" name="musical_vl" value="0,00" required id="id_musical_vl" class="form-control edValor" /></td>
       </tr>
       <tr>
        <td>Vestuário</td>
        <td><input type="number" name="vestuario_qt" value="0" min="0" required id="id_vestuario_qt" class="form-control" /></td>
        <td><input type="text" name="vestuario_vl" value="0,00" required id="id_vestuario_vl" class="form-control edValor" /></td>
       </tr>
       <tr>
        <td>Higiene Pessoal, Perfumes e Cosméticos</td>
        <td><input type="number" name="perfume_qt" value="0" min="0" required id="id_perfume_qt" class="form-control" /></td>
        <td><input type="text" name="perfume_vl" value="0,00" required id="id_perfume_vl" class="form-control edValor" /></td>
       </tr>
        <tr>
        <td colspan="3"><hr></td>
          </tr>
            <tr>
          <td>Valor Total</td>
          <td colspan="2"><input type="text" readonly id="id_total" class="form-control" /></td>
      </tr>
        <tr>
        <td colspan="3"><hr></td>
      </tr>
      <tr>
        <td colspan="3"><button class="btn btn-primary btn-lg btn-block" type="submit">Salvar</button></td>
      </tr>
    </table>



</form>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$( document ).ready(function() {
    $("#id_brinquedo_qt").focus().select();

    $('.edValor').blur( function() {
        var total = 0.00;
        $('.edValor').each(function(){
            total = parseFloat($(this).val().replace(',', '.')) + parseFloat(total);
        });
        $('#id_total').val(total.toFixed(2).replace('.', ','));
    });

});
</script>
{% endblock %}